name: Compile and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Update Definitions
        run: npm run defs

      - name: Compile TypeScript
        run: npx tsc

      - name: Copy Compiled Files
        run: |
          git config user.name "Rhylei"
          git config user.email "Rhylei@aureate.dev"
          git checkout --orphan compiled
          rm -rf *
          cp -r dist/* .
          git add .
          git commit -m "Update compiled files"
          git push origin compiled --force
